#!/usr/bin/env python
"""Judge style positive control — validates the VLM judge can recognize a target style AT ALL
before any `style_adherence` number derived from it is trusted, per
docs/WEIGHT_SWEEP_PREREGISTRATION.md.

DO NOT RUN until the weight sweep (scripts/_pattachitra_weight_sweep.py) has finished and the GPU
is free — this makes ~223 new Ollama VLM calls, and Ollama serves `qwen2.5vl:7b` on the same GPU
the sweep's SDXL pipeline is using (confirmed: `nvidia-smi --query-compute-apps` shows
`ollama/lib/ollama/llama-server.exe` holding several GB of VRAM whenever the judge model is
loaded). No SDXL generation happens in this script at all — every image it scores already exists
on disk (real training corpus photos, or already-generated `sdxl_base` outputs).

CRITICAL FINDING THIS SCRIPT EXISTS TO TEST FOR (discovered by direct inspection of
scripts/model_verdict_harness.py's `SINGLE_AXIS_JUDGE_PROMPTS`, before this script was ever run):
the `style_adherence` judge question was **hardcoded** to ask "does this image look like an
authentic Ukiyo-e (Japanese woodblock print)" — regardless of which project called
`score_vlm_judge()`. `scripts/_pattachitra_ab_base_comparison.py` reused that exact function,
unmodified. **Every Pattachitra `style_adherence` score recorded before the fix below — all 360
records in `reports/pattachitra_ab_base_comparison.json`, the entire primary endpoint A of
`docs/MODEL_VERDICT.md` §7 — was generated by asking the judge whether the image looks like
ukiyo-e, not Pattachitra.** This has since been FIXED (`score_vlm_judge` now requires an explicit
`style_question` from every caller, no hardcoded default) — this positive control tests the
now-historical broken behavior directly, not a live harness code path, so its result is unaffected
by the fix landing first. This script tests two distinct prompt variants for Pattachitra, not one:

  (A) HISTORICAL/PRODUCTION-AS-RECORDED — the literal text that was hardcoded before the fix
      (`HISTORICAL_UKIYO_E_QUESTION`, frozen here since the harness no longer carries a default to
      import). Tests whether the numbers *already in* `docs/MODEL_VERDICT.md` are trustworthy as
      recorded.
  (B) CORRECTED — the domain-appropriate prompt for Pattachitra now used in production
      (`PATTACHITRA_STYLE_QUESTION`, matching `scripts/_pattachitra_ab_base_comparison.py`'s own
      constant, grounded in `docs/NEXT_MODEL_SPEC.md`'s corpus-quality table: "flat colour, dense
      ornamental border, circular iconographic composition" — not a newly-invented description).
      Tests whether the judge CAN recognize Pattachitra style when actually asked about it.

For ukiyo-e, (A) and (B) are identical (`UKIYO_E_STYLE_QUESTION`, imported from the harness — no
bug exists there, before or after the fix) — ukiyo-e is scored once and serves as the
expected-pass case that validates this control's own methodology.

## Design

- **Real reference images** (indisputably authentic examples of each style):
  - Pattachitra: the 100-image curated training corpus, `data/lora/pattachitra-curated/images/`.
  - Ukiyo-e: the 23-image curated training corpus, `data/lora/ukiyo-e-curated/images/`.
- **Comparison arm — already-generated `sdxl_base` outputs, no regeneration:**
  - Pattachitra: `reports/pattachitra_ab_base_comparison.json`'s `checkpoint == "base"` records
    (n=90; `sdxl_base`, no LoRA, on the `pat_*` prompt set, which already includes the word
    "Pattachitra" and the `pattascroll` trigger token in every prompt's text).
  - Ukiyo-e: `reports/lora_ab_base_comparison.json` (n=90; `sdxl_base`, no LoRA, on the
    `ukyowood`-triggered prompt set) — the direct ukiyo-e analog of the Pattachitra base arm above.
- **Scoring:** one Ollama call per (image, prompt-variant) — `model_verdict_harness`'s own
  `_ollama_generate_json`, reused directly, not reimplemented. `qwen2.5vl:7b`, zero paid APIs.
- **Statistics — UNPAIRED, not this project's usual paired design.** There is no natural 1:1
  pairing between a specific real training photograph and a specific generated (prompt, seed)
  image, and the two groups have different, unrelated `n` (100 or 23 vs. 90). SEM combines via
  independent-sample quadrature (`sqrt(var_a/n_a + var_b/n_b)`), not the paired-diff-on-matched-
  keys SEM used everywhere else in this project. This is the one endpoint in the whole audit that
  is genuinely a two-sample comparison, and is treated as one, not silently forced into a paired
  frame it doesn't fit.

## Decision rule (pre-registered here and in docs/WEIGHT_SWEEP_PREREGISTRATION.md, BEFORE running)

- **PASS** for a given (domain, prompt-variant): real reference images score `style_adherence`
  higher than `sdxl_base` outputs by `diff/SEM > +2.0` (unpaired).
- **Ukiyo-e is the expected-pass case, validating the control itself.** If ukiyo-e does NOT pass,
  the control methodology (not just the Pattachitra domain) is suspect and must be fixed before
  trusting any Pattachitra result from it.
- **If ukiyo-e PASSES and Pattachitra FAILS on the PRODUCTION prompt:** confirms the numbers
  already in `docs/MODEL_VERDICT.md` §7 are measuring the wrong thing (asking about ukiyo-e for
  Pattachitra images). Mark every existing Pattachitra `style_adherence` number as
  **UNINFORMATIVE**, not as evidence about the adapter.
- **If Pattachitra additionally FAILS on the CORRECTED prompt:** the judge is insensitive to
  Pattachitra style even when properly asked. Mark every Pattachitra `style_adherence` number as
  uninformative for a *different* reason (instrument blindness on this domain, not a wrong
  question) — and do not try a third prompt variant looking for one that "works"; that would be
  p-hacking the rubric itself, not validating it.
- **If Pattachitra PASSES on the CORRECTED prompt (having failed on PRODUCTION):** cleanly
  demonstrates the judge is not blind to Pattachitra — the deployed question was simply wrong. A
  re-score with the corrected prompt is required before any style-lift conclusion about the
  adapter can be drawn; the existing numbers are still not usable as recorded.
- **If BOTH ukiyo-e and Pattachitra fail:** the `style_adherence` axis is unreliable across
  domains generally, and the *ukiyo-e* style numbers need the same "uninformative" treatment too —
  not just Pattachitra's.

**Corroborating, non-sufficient context (not independent proof):** `artifact_absence` is pinned at
exactly 1.0 with zero variance across all 360 Pattachitra records (checked directly against
`reports/pattachitra_ab_base_comparison.json`, not the "180" figure floated when this script was
commissioned — verified count is 360 = 90 base + 90×3 curated checkpoints). A non-discriminating
axis is *consistent with* judge insensitivity to this domain, but `docs/MODEL_VERDICT.md` §7.5
already offers a competing, equally plausible explanation (Pattachitra prompts genuinely don't
evoke SDXL's text/caption-artifact tendency the way ukiyo-e prompts do) — the ceiling effect alone
cannot distinguish these two explanations. This script's `style_adherence` result is the decisive
test, not the `artifact_absence` ceiling.

Usage:
    python scripts/judge_style_positive_control.py
"""

from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).parent.parent))

from aetherart.logger import get_logger

logger = get_logger(__name__)

ROOT = Path(__file__).parent.parent
OUT_JSON = ROOT / "reports" / "judge_style_positive_control.json"

PATTACHITRA_REAL_DIR = ROOT / "data" / "lora" / "pattachitra-curated" / "images"
UKIYO_E_REAL_DIR = ROOT / "data" / "lora" / "ukiyo-e-curated" / "images"
PATTACHITRA_BASE_JSON = ROOT / "reports" / "pattachitra_ab_base_comparison.json"
UKIYO_E_BASE_JSON = ROOT / "reports" / "lora_ab_base_comparison.json"

Z_ALPHA_2 = 1.96
Z_BETA_80 = 0.8416
Z_BETA_90 = 1.2816

# (B) — grounded in docs/NEXT_MODEL_SPEC.md's own already-vetted corpus-quality description of
# Pattachitra, not a newly-invented aesthetic. Mirrors the production prompt's structure/length.
# harness.UKIYO_E_STYLE_QUESTION (imported in main(), not re-transcribed by hand) serves double
# duty here: it is ukiyo-e's own correct, current production question, AND - unchanged - it is
# exactly the wrong question that was historically asked of every Pattachitra image before the
# fix (the harness no longer carries a Pattachitra-specific default to import, by design, so the
# only faithful way to reproduce "the exact text that produced the 360 existing scores" is via
# the ukiyo-e constant that was, and remains, that literal text).

# Matches scripts/_pattachitra_ab_base_comparison.py's PATTACHITRA_STYLE_QUESTION exactly -
# grounded in docs/NEXT_MODEL_SPEC.md's own prior corpus-quality description, not invented.
PATTACHITRA_STYLE_QUESTION = (
    "does this image look like an authentic Pattachitra painting (traditional Odisha folk art) - "
    "flat colour, dense ornamental border, circular iconographic composition?"
)


def _wrap_style_question(style_question: str) -> str:
    """Mirrors harness.score_vlm_judge's internal style_adherence prompt construction exactly, so
    this control tests byte-for-byte the same request shape production sends - not an
    approximation of it."""
    return (
        "You are judging a single image against one question only.\n"
        f"Question: {style_question}\n"
        'Respond with ONLY a JSON object: {"style_adherence": <float 0.0-1.0>}'
    )


def _import_harness():
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "model_verdict_harness", ROOT / "scripts" / "model_verdict_harness.py"
    )
    mod = importlib.util.module_from_spec(spec)
    sys.modules["model_verdict_harness"] = mod
    spec.loader.exec_module(mod)
    return mod


def score_style_adherence(harness, img: Image.Image, prompt_text: str) -> float | None:
    """One Ollama call, one axis - mirrors harness.score_vlm_judge's per-axis mechanism exactly,
    but for a single, caller-supplied prompt variant rather than the harness's fixed axis set."""
    import base64
    import io

    buf = io.BytesIO()
    img.save(buf, format="PNG")
    b64 = base64.b64encode(buf.getvalue()).decode()
    try:
        result = harness._ollama_generate_json(prompt_text, b64)
        value = float(result["style_adherence"])
    except Exception as e:
        logger.warning("Positive-control judge call failed: %s", e)
        return None
    if not 0.0 <= value <= 1.0 or value != value:  # value != value catches NaN
        logger.warning("Positive-control judge score out of range/NaN: %s", value)
        return None
    return value


def score_images(harness, image_paths: list[Path], prompt_text: str) -> list[float]:
    scores = []
    for i, path in enumerate(image_paths):
        img = Image.open(path)
        score = score_style_adherence(harness, img, prompt_text)
        if score is not None:
            scores.append(score)
        if (i + 1) % 20 == 0 or i == len(image_paths) - 1:
            logger.info(
                "[positive-control] [%d/%d] %s: %s", i + 1, len(image_paths), path.name, score
            )
    return scores


def unpaired_stats(sample_a: list[float], sample_b: list[float]) -> dict:
    """Two-sample (unpaired) diff/SEM: a = real reference images (expected higher), b = sdxl_base
    outputs. diff = mean(a) - mean(b); SEM via independent-sample quadrature - NOT this project's
    usual paired-diff-on-matched-keys SEM, because there is no natural pairing here (see module
    docstring)."""
    n_a, n_b = len(sample_a), len(sample_b)
    mean_a, mean_b = statistics.fmean(sample_a), statistics.fmean(sample_b)
    var_a = statistics.variance(sample_a) if n_a > 1 else 0.0
    var_b = statistics.variance(sample_b) if n_b > 1 else 0.0
    diff = mean_a - mean_b
    sem = (var_a / n_a + var_b / n_b) ** 0.5
    ratio = diff / sem if sem else (float("inf") if diff != 0 else 0.0)
    return {
        "n_a": n_a,
        "n_b": n_b,
        "mean_a": round(mean_a, 4),
        "mean_b": round(mean_b, 4),
        "diff": round(diff, 4),
        "sem": round(sem, 4),
        "diff_over_sem": round(ratio, 3),
        "mde_80pct_power": round((Z_ALPHA_2 + Z_BETA_80) * sem, 4),
        "mde_90pct_power": round((Z_ALPHA_2 + Z_BETA_90) * sem, 4),
        "passes_2xsem": diff > 0 and ratio > 2.0,
    }


def load_base_scores(path: Path, checkpoint_filter: str | None) -> list[float]:
    records = json.loads(path.read_text(encoding="utf-8"))
    if checkpoint_filter is not None:
        records = [r for r in records if r.get("checkpoint") == checkpoint_filter]
    return [
        r["independent_calls"]["style_adherence"]
        for r in records
        if not r.get("error") and r.get("independent_calls")
    ]


def main() -> None:
    harness = _import_harness()

    pattachitra_real_paths = sorted(PATTACHITRA_REAL_DIR.glob("*.jpg"))
    ukiyo_e_real_paths = sorted(UKIYO_E_REAL_DIR.glob("*.jpg"))
    assert len(pattachitra_real_paths) == 100, f"expected 100, got {len(pattachitra_real_paths)}"
    assert len(ukiyo_e_real_paths) == 23, f"expected 23, got {len(ukiyo_e_real_paths)}"

    pattachitra_base_scores = load_base_scores(PATTACHITRA_BASE_JSON, checkpoint_filter="base")
    ukiyo_e_base_scores = load_base_scores(UKIYO_E_BASE_JSON, checkpoint_filter=None)
    assert len(pattachitra_base_scores) == 90, f"expected 90, got {len(pattachitra_base_scores)}"
    assert len(ukiyo_e_base_scores) == 90, f"expected 90, got {len(ukiyo_e_base_scores)}"

    ukiyo_e_prompt = _wrap_style_question(harness.UKIYO_E_STYLE_QUESTION)
    # Same text as ukiyo_e_prompt - see the constant's own comment for why this is not a
    # transcription error. Named separately so the two roles this text plays (correct for
    # ukiyo-e, historically wrong for Pattachitra) read as distinct in the results below.
    historical_wrong_prompt_for_pattachitra = ukiyo_e_prompt
    pattachitra_corrected_prompt = _wrap_style_question(PATTACHITRA_STYLE_QUESTION)

    results = {}

    logger.info("[positive-control] Scoring ukiyo-e real images (production prompt, n=23)...")
    ukiyo_e_real_scores = score_images(harness, ukiyo_e_real_paths, ukiyo_e_prompt)
    results["ukiyo_e"] = unpaired_stats(ukiyo_e_real_scores, ukiyo_e_base_scores)

    logger.info(
        "[positive-control] Scoring Pattachitra real images "
        "(HISTORICAL/ukiyo-e-worded prompt, n=100)..."
    )
    pattachitra_real_historical = score_images(
        harness, pattachitra_real_paths, historical_wrong_prompt_for_pattachitra
    )
    results["pattachitra_production_prompt"] = unpaired_stats(
        pattachitra_real_historical, pattachitra_base_scores
    )

    logger.info(
        "[positive-control] Scoring Pattachitra real images "
        "(CORRECTED/Pattachitra-worded prompt, n=100)..."
    )
    pattachitra_real_corrected = score_images(
        harness, pattachitra_real_paths, pattachitra_corrected_prompt
    )
    results["pattachitra_corrected_prompt"] = unpaired_stats(
        pattachitra_real_corrected, pattachitra_base_scores
    )

    print("=== Judge style positive control (n unpaired) ===\n")
    for key, stats in results.items():
        print(f"--- {key} ---")
        print(
            f"  real mean={stats['mean_a']:.4f} (n={stats['n_a']})  "
            f"base mean={stats['mean_b']:.4f} (n={stats['n_b']})"
        )
        print(
            f"  diff={stats['diff']:+.4f}  SEM={stats['sem']:.4f}  "
            f"diff/SEM={stats['diff_over_sem']:.3f}  "
            f"MDE@80%={stats['mde_80pct_power']:.4f}  MDE@90%={stats['mde_90pct_power']:.4f}"
        )
        print(f"  {'PASS' if stats['passes_2xsem'] else 'FAIL'} (>2xSEM threshold)\n")

    ukiyo_e_pass = results["ukiyo_e"]["passes_2xsem"]
    pattachitra_prod_pass = results["pattachitra_production_prompt"]["passes_2xsem"]
    pattachitra_corr_pass = results["pattachitra_corrected_prompt"]["passes_2xsem"]

    print("=== Verdict (decision rule fixed in advance - see module docstring) ===")
    if not ukiyo_e_pass:
        print(
            "Ukiyo-e (expected-pass case) FAILED. The control methodology itself is suspect - "
            "do not trust any Pattachitra result from this run without fixing that first."
        )
    elif pattachitra_prod_pass:
        print(
            "Unexpected: Pattachitra PASSED on the production (ukiyo-e-worded) prompt. "
            "Re-examine before accepting - this was not the predicted outcome."
        )
    elif pattachitra_corr_pass:
        print(
            "Pattachitra FAILED on the production prompt but PASSED on the corrected prompt: "
            "the judge is not blind to Pattachitra style - the deployed question was wrong. "
            "Every existing Pattachitra style_adherence number is UNINFORMATIVE as recorded; "
            "a re-score with the corrected prompt is required before any style-lift claim."
        )
    else:
        print(
            "Pattachitra FAILED on BOTH the production and corrected prompts: the judge is "
            "insensitive to Pattachitra style even when properly asked. Every existing "
            "Pattachitra style_adherence number is UNINFORMATIVE for a different reason "
            "(instrument blindness on this domain) - not evidence the adapter has no lift."
        )

    OUT_JSON.write_text(
        json.dumps(
            {
                "results": results,
                "ukiyo_e_pass": ukiyo_e_pass,
                "pattachitra_production_prompt_pass": pattachitra_prod_pass,
                "pattachitra_corrected_prompt_pass": pattachitra_corr_pass,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"\nWritten: {OUT_JSON}")


if __name__ == "__main__":
    main()
